services:
    signaling.topic_service:
        class: AppBundle\Topic\SignalingTopic
        tags:
            - { name: gos_web_socket.topic }

    api_exception_subscriber:
        class: AppBundle\EventListener\ApiExceptionSubscriber
        arguments: ['%kernel.debug%', '@api.response_factory', '@logger']
        tags:
            - { name: kernel.event_subscriber }

    jwt_token_authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        autowire: true

    api.response_factory:
        class: AppBundle\Api\ResponseFactory